image: your:image
  
stages:
  - start notification
  - build
  - deploy
  - error notification

start_notify:
  stage: start notification
  tags:
    - test
  script:
    - bash .ci-notify.sh start

build:
  stage: build
  tags:
    - test
  script:
    - script_for_build

deploy:
  stage: deploy
  tags:
    - test
  script:
    - script_for_deploy
    - bash .ci-notify.sh success

notify:
  stage: error notification
  tags:
    - test
  script:
    - bash .ci-notify.sh faile
  when: on_failure